steps:
# Run the deployment script. NOTE: the IATA depends on the region where the
# VM is deployed. Our testing VM is always in us-central1, which is OMA.
- name: us-central1-docker.pkg.dev/$PROJECT_ID/build-images/gcloud-jsonnet-cbif:1.1
  dir: '/workspace/'
  args: [
    '/workspace/deploy.sh $PROJECT_ID mlab ${_API_KEY} ${_PROBABILITY}'
  ]
