version: '3.7'
services:
  # Register this node with the Autojoin API. A successful registration will
  # assign a DNS name for this node based on the public IPs, their ASN,
  # organiztion, and IATA code. As well, Register distributes other credentials
  # needed to upload and archive measurement data. The register command contacts
  # the Autojoin API every hour.
  register-node:
    # NOTE: register should not be restarted on failure.
    image: measurementlab/autojoin-register:${DOCKER_TAG}
    pull_policy: always
    network_mode: host
    volumes:
      - ./autonode:/autonode
    command:
      - -endpoint=https://autojoin-dot-${PROJECT}.appspot.com/autojoin/v0/node/register
      - -key=${API_KEY}
      - -service=ndt
      - -organization=${ORGANIZATION}
      - -iata=${IATA}
      - -output=/autonode
      - -healthcheck-addr=:8001
      - -ports=9990,9991,9992,9993
      - -probability=${PROBABILITY}
      - -ipv4=${IPV4}
      - -ipv6=${IPV6}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/ready"]
      interval: 3s
      timeout: 5s
      retries: 10

  # ndt-server is the public facing measurement service. Only ndt7 is enabled.
  ndt-server:
    image: measurementlab/ndt-server:v0.23.0
    network_mode: host
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - ./certs:/certs
      - ./html:/html
      - ./schemas:/schemas
      - ./resultsdir:/resultsdir
      - ./autonode:/autonode
      - ./autocert:/autocert
    depends_on:
      generate-schemas-ndt7:
        condition: service_completed_successfully
      generate-uuid:
        condition: service_completed_successfully
      register-node:
        condition: service_healthy
    restart: always
    # NOTE: All containers will use the host network. All the following ports
    # must not be in use.
    ports:
      # ndt-server TLS and non-TLS ports.
      - target: 443
        published: 443
        protocol: tcp
      - target: 80
        published: 80
        protocol: tcp
      # ndt-server prometheus.
      - target: 9990
        published: 9990
        protocol: tcp
      # jostler prometheus.
      - target: 9991
        published: 9991
        protocol: tcp
      # annotator prometheus.
      - target: 9992
        published: 9992
        protocol: tcp
      # heartbeat prometheus.
      - target: 9993
        published: 9993
        protocol: tcp
      # traceroute-caller prometheus.
      - target: 9994
        published: 9994
        protocol: tcp
    command:
      - -uuid-prefix-file=/schemas/uuid.prefix
      - -datadir=/resultsdir/ndt
      - -ndt7_addr=:443
      - -ndt7_addr_cleartext=:80
      # Allow ndt7 data to be autoloaded.
      - -compress-results=false
      # TODO(host): confirm device name.
      - -txcontroller.device=${INTERFACE_NAME}
      - -txcontroller.max-rate=${INTERFACE_MAXRATE}
      - -prometheusx.listen-address=:9990
      # Add server metadata.
      - -label=type=virtual
      - -label=deployment=byos
      - -label=managed=none
      - -label=loadbalanced=false
      - -label=org=${ORGANIZATION}
      # Effectively disable ndt5.
      - -ndt5_addr=127.0.0.1:3002
      - -ndt5_ws_addr=127.0.0.1:3001
      - -tcpinfo.eventsocket=/schemas/events.sock
      - -autocert.enabled=true
      - -autocert.hostname=@/autonode/hostname
      - -token.machine=@/autonode/hostname
      - -token.verify-key=/locate/verify.pub
      - -ndt7.token.required=true
    configs:
      - source: locate-verify-key
        target: /locate/verify.pub

  # heartbeat reports health and liveness messages to M-Lab's Locate API every
  # 10sec. The Locate API is responsible for directing clients to nearby healthy
  # servers.
  heartbeat:
    image: measurementlab/heartbeat:v0.14.48
    volumes:
      - ./autonode:/autonode
    depends_on:
      ndt-server:
        condition: service_started
      register-node:
        condition: service_healthy
    restart: always
    command:
      - -prometheusx.listen-address=:9993
      - -experiment=ndt
      - -hostname-file=/autonode/hostname
      - -registration-url=file:///autonode/registration.json
      - -heartbeat-url=wss://${LOCATE_URL}/v2/platform/heartbeat?key=${API_KEY}
      - -services=ndt/ndt7=ws:///ndt/v7/download,ws:///ndt/v7/upload,wss:///ndt/v7/download,wss:///ndt/v7/upload
    network_mode: host

  # uuid-annotator records network and geographic annotations based on the
  # client and server IP so each NDT measurement is annotated in BigQuery.
  uuid-annotator:
    image: measurementlab/uuid-annotator:v0.5.9
    volumes:
      - ./resultsdir:/resultsdir
      - ./schemas:/schemas
      - ./certs:/certs
      - ./autonode:/autonode
    depends_on:
      ndt-server:
        condition: service_started
      register-node:
        condition: service_healthy
    network_mode: host
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/autonode/service-account-autojoin.json
    restart: always
    # NOTE: all database URLs are required.
    command:
      - -prometheusx.listen-address=:9992
      - -datadir=/resultsdir/ndt/annotation2
      - -tcpinfo.eventsocket=/schemas/events.sock
      - -ipservice.sock=/schemas/uuid-annotator.sock
      - -maxmind.url=gs://downloader-${PROJECT}/Maxmind/current/GeoLite2-City.tar.gz
      - -routeview-v4.url=gs://downloader-${PROJECT}/RouteViewIPv4/current/routeview.pfx2as.gz
      - -routeview-v6.url=gs://downloader-${PROJECT}/RouteViewIPv6/current/routeview.pfx2as.gz
      - -siteinfo.url=file:///autonode/annotation.json
      - -hostname-file=/autonode/hostname

  # jostler archives the raw data from ndt-server and the uuid-annotator into
  # JSONL "bundles". These bundles are uploaded to GCS using credentials from
  # register. Jostler depends on the local schemas being up to date or backward
  # compatible with upstream schemas.
  jostler:
    image: measurementlab/jostler:v1.1.3
    volumes:
      - ./resultsdir:/resultsdir
      - ./schemas:/schemas
      - ./certs:/certs
      - ./autonode:/autonode
    network_mode: host
    depends_on:
      generate-schemas-ndt7:
        condition: service_completed_successfully
      generate-schemas-annotation2:
        condition: service_completed_successfully
      register-node:
        condition: service_healthy
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/autonode/service-account-autojoin.json
    # NOTE: jostler should not restart on exit.
    command:
      - -mlab-node-name-file=/autonode/hostname
      # NOTE: the ndt7 schema must already exist in the target bucket.
      - -gcs-bucket=archive-${PROJECT}
      - -gcs-data-dir=autoload/v2
      - -local-data-dir=/resultsdir
      - -organization=${ORGANIZATION}
      - -experiment=ndt
      - -datatype=ndt7
      - -datatype-schema-file=ndt7:/schemas/ndt7.json
      - -datatype=annotation2
      - -datatype-schema-file=annotation2:/schemas/annotation2.json
      - -bundle-size-max=20971520
      - -bundle-age-max=1h
      - -missed-age=2h
      - -missed-interval=5m
      - -extensions=.json
      - -upload-schema=false
      - -verbose
      - -prometheusx.listen-address=:9991

  traceroute-caller:
    # TODO(soltesz): update image version.
    image: measurementlab/traceroute-caller:sandbox-soltesz-autoloadable
    volumes:
      - ./resultsdir:/resultsdir
      - ./schemas:/schemas
    #  - ./certs:/certs
    #  - ./autonode:/autonode
    command:
      - -uuid-prefix-file=/schemas/uuid.prefix
      - -prometheusx.listen-address=:9994
      - -traceroute-output=/resultsdir/ndt/scamper2
      - -hopannotation-output=/resultsdir/ndt/hopannotation1
      - -tcpinfo.eventsocket=/schemas/events.sock
      - -IPCacheTimeout=10m
      - -IPCacheUpdatePeriod=1m
      - -scamper.timeout=30m
      - -scamper.tracelb-W=15
      - -ipservice.sock=/schemas/uuid-annotator.sock
      - -anonymize.ip=none
      - -scamper.trace-type=regular

  # Generate the schemas needed by jostler to assess that the data is backward
  # compatible with upstream schemas and safe to upload.
  generate-schemas-ndt7:
    network_mode: host
    image: measurementlab/ndt-server:v0.22.0
    volumes:
      - ./schemas:/schemas
    entrypoint:
    - /generate-schemas
    - -ndt7=/schemas/ndt7.json

  generate-schemas-annotation2:
    network_mode: host
    image: measurementlab/uuid-annotator:v0.5.8
    volumes:
      - ./schemas:/schemas
    entrypoint:
    - /generate-schemas
    - -ann2=/schemas/annotation2.json

  generate-schemas-tracreoute:
    network_mode: host
    # TODO(soltesz): update image version.
    image: measurementlab/traceroute-caller:sandbox-soltesz-autoloadable
    volumes:
      - ./schemas:/schemas
    entrypoint:
    - /generate-schemas
    - -scamper2=/schemas/scamper2.json
    - -hopannotation1=/schemas/hopannotation1.json

  # Generate the uuid prefix needed by the ndt-server and uuid-annotator.
  generate-uuid:
    network_mode: host
    image: measurementlab/uuid:v1.0.0
    volumes:
      - ./schemas:/schemas
    command:
      - -filename=/schemas/uuid.prefix

configs:
  locate-verify-key:
    content: |
      {"use":"sig","kty":"OKP","kid":"locate_20200409","crv":"Ed25519","alg":"EdDSA","x":"1tS1d-dd2B-VRBTWzOaq7zUngKDyV409K-o42LN2nx8"}
