version: '3.7'
services:
  ndt-server:
    image: measurementlab/ndt-server:v0.22.0
    network_mode: host
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - ./certs:/certs
      - ./schemas:/schemas
      - ./resultsdir:/resultsdir
      - ./autonode:/autonode
      - ./autocert:/autocert
    # NOTE: All containers will use the host network. All the following ports
    # must not be in use.
    ports:
      # ndt-server TLS and non-TLS ports.
      - target: 443
        published: 443
        protocol: tcp
      - target: 8080
        published: 8080
        protocol: tcp
      # ndt-server prometheus.
      - target: 9990
        published: 9990
        protocol: tcp
      # jostler prometheus.
      - target: 9991
        published: 9991
        protocol: tcp
      # annotator prometheus.
      - target: 9992
        published: 9992
        protocol: tcp
      # heartbeat prometheus.
      - target: 9993
        published: 9993
        protocol: tcp
    command:
      - -datadir=/resultsdir/ndt
      - -ndt7_addr_cleartext=:8080
      # Allow ndt7 data to be autoloaded.
      - -compress-results=false
      - -txcontroller.device=eth0
      - -txcontroller.max-rate=150000000
      - -prometheusx.listen-address=:9990
      # Effectively disable ndt5.
      - -ndt5_addr=127.0.0.1:3002
      - -ndt5_ws_addr=127.0.0.1:3001
      - -tcpinfo.eventsocket=/schemas/events.sock
